# Generated by Django 5.2.1 on 2025-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('oid', models.CharField(blank=True, max_length=150)),
                ('amountpaid', models.IntegerField(blank=True, max_length=500, null=True)),
                ('paymentstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
