# Generated by Django 5.2.1 on 2025-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_rename_order_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('oid', models.CharField(blank=True, max_length=150)),
                ('amountpaid', models.IntegerField(blank=True, null=True)),
                ('paymentstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
